---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  tasks:
  - name: run script
    command: /bin/sh './ansible/part1_create_vm.sh'
    #- debug: msg="the echo was {{ role_path }}/files/part1_create_vm.sh"
